[package]
name = 'pallet-exchange'
description = 'dex prototype'
repository = 'https://github.com/sunriseprotocol/sunrise'
authors = ['Sunrise']
version = '2.0.0'
edition = '2018'

[dependencies]
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false }
frame-support = { default-features = false, version = '2.0.1' }
frame-system = { default-features = false, version = '2.0.0' }
sp-runtime = { default-features = false, version = '2.0.0' }

orml-traits = { default-features = false, version = '0.3.0' }
orml-utilities = { default-features = false, version = '0.3.0' }
pallet-srstokens = { default-features = false, path = "../srstoken" }

[dev-dependencies]
sp-core = { default-features = false, version = '2.0.0' }
sp-io = { default-features = false, version = '2.0.0' }


[features]
default = ['std']
std = [
	'serde',
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-runtime/std',
    'orml-traits/std',
    'orml-utilities/std',
    'pallet-srstokens/std',
]
