[package]
authors = ['Sunrise Protocol']
build = 'build.rs'
description = 'Sunrise Node'
edition = '2018'
homepage = 'https://sunriseprotocol.com'
license = 'Apache 2.0'
name = 'dawn-collator'
repository = 'https://github.com/sunriseprotocol/sunrise'
version = '0.1.0'
[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
futures = "0.3.4"
parity-util-mem = { version = "0.8.0", default-features = false, features = ["jemalloc-global"] }
sunrise-cli = { path = "cli" }
sunrise-service = { path = "service" }
sunrise-runtime = { path = "../../runtime/sunrise", optional = true }

[[bin]]
name = 'dawn-collator'

[features]
default = []
runtime-benchmarks = ['sunrise-runtime/runtime-benchmarks']
