[package]
name = "fp-rpc"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io"]
edition = "2018"
description = "Runtime primitives for Ethereum RPC (web3) compatibility layer for Substrate."
license = "Apache-2.0"

[dependencies]
sp-core = { version = "2.0.0-dev", default-features = false }
sp-api = { version = "2.0.0-dev", default-features = false}
fp-evm = { version = "0.8.0", default-features = false, path = "../../primitives/evm" }
ethereum = { version = "0.6", default-features = false, features = ["with-codec"] }
ethereum-types = { version = "0.10", default-features = false }
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false }
sp-runtime = { version = "2.0.0-dev", default-features = false}
sp-std = { version = "2.0.0-dev", default-features = false }
sp-io = { version = "2.0.0", default-features = false}

[features]
default = ["std"]
std = [
	"sp-core/std",
	"sp-api/std",
	"fp-evm/std",
	"ethereum/std",
	"ethereum-types/std",
	"codec/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-io/std",
]
